preserve_hierarchy: true
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  - source: /ReGuilded/Resources/ReGuildedLang.resx
    translation: /ReGuilded/Resources/%file_name%.%locale%.%file_extension%
